/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StatusLog } from "./StatusLog";
import { StatusLogCountArgs } from "./StatusLogCountArgs";
import { StatusLogFindManyArgs } from "./StatusLogFindManyArgs";
import { StatusLogFindUniqueArgs } from "./StatusLogFindUniqueArgs";
import { DeleteStatusLogArgs } from "./DeleteStatusLogArgs";
import { StatusLogService } from "../statusLog.service";
@graphql.Resolver(() => StatusLog)
export class StatusLogResolverBase {
  constructor(protected readonly service: StatusLogService) {}

  async _statusLogsMeta(
    @graphql.Args() args: StatusLogCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StatusLog])
  async statusLogs(
    @graphql.Args() args: StatusLogFindManyArgs
  ): Promise<StatusLog[]> {
    return this.service.statusLogs(args);
  }

  @graphql.Query(() => StatusLog, { nullable: true })
  async statusLog(
    @graphql.Args() args: StatusLogFindUniqueArgs
  ): Promise<StatusLog | null> {
    const result = await this.service.statusLog(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StatusLog)
  async deleteStatusLog(
    @graphql.Args() args: DeleteStatusLogArgs
  ): Promise<StatusLog | null> {
    try {
      return await this.service.deleteStatusLog(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
